### ISSUE TITLE
Put NodeList first in the PHPDoc blocks for fields that return them

### ISSUE THREAD

**Issue by spawnia** [webonyx/graphql-php#285]
When working with the AST, i found that variables that contain references to multiple children are defined as typed arrays, for example in https://github.com/webonyx/graphql-php/blob/master/src/Language/AST/ObjectTypeDefinitionNode.php

However, they do actually return a `NodeList`, for example:

````php
>>> GraphQL\Language\Parser::parse('type Foo { bar: Int }')->definitions[0]->fields
=> GraphQL\Language\AST\NodeList {#951}

>>> GraphQL\Language\Parser::parse('type Foo { bar(baz: Int): Int }')->definitions[0]->fields[0]->arguments
=> GraphQL\Language\AST\NodeList {#1046}
````

I think the return type should match the definition to avoid surprises.

Additionally, the behaviour for how empty lists function may differ:

````php
>>> GraphQL\Language\Parser::parse('type Foo {}')->definitions[0]->fields
=> GraphQL\Language\AST\NodeList {#1012}

>>> GraphQL\Language\Parser::parse('type Foo { bar: Int }')->definitions[0]->fields[0]->arguments
=> []
````

This has caused me trouble when trying to use `merge()` on the arguments of a field.

**Comment by vladar** [comment]
Yeah, the code base starves for a cleanup and maybe some code style analysis applied. PRs welcome! %) 

This particular issue is caused by the fact that originally lists were just arrays, but docblocks were not updated.

**Comment by vladar** [comment]
Looks like I misunderstood the following note:
```php
GraphQL\Language\Parser::parse('type Foo { bar: Int }')->definitions[0]->fields[0]->arguments
=> []
```
If it's the case, then it is a bug. AST must contain `NodeList` here. But I can't reproduce it. For me it returns `NodeList`, not `[]`.

Which version do you use? Can you double check with the latest?

**Comment by spawnia** [comment]
It does return `NodeList` in v0.12.4 indeed, so that seems like it was fixed.

However, the main issue actually is that the return types for lists of nodes are still not correct. While it would certainly be an easy fix to change them all to NodeList, i do not quite like that this would then hide the underyling type.

**Comment by vladar** [comment]
Yeah, that was a primary reason why they are marked as `SomeNode[]`. This has more value over just `NodeList`.

PHP type annotations are too weak to express complex types. Maybe some IDEs do support things like `NodeList<SomeNode>` but obviously not all of them.

**Comment by vladar** [comment]
For me, it's rather pragmatic - IDEs must correctly handle such definitions. If this notation enables better IDE support - this is great. But if it breaks them, then it's a problem.

**Comment by vladar** [comment]
DocBlocks should be fixed via PR #323

**Comment by spawnia** [comment]
As i mentioned in a comment, i think #323 has the DocBlocks the wrong way around. The actual type should come first (NodeList) and the pseudo-type second.

**Comment by spawnia** [comment]
@vladar #323 does not fix this, as the typehint is still wrong. Please reopen

**Comment by vladar** [comment]
You mean the reverse order of type hints?

**Comment by vladar** [comment]
Those hints are just workarounds anyway. Only parameterized types in PHP type system would allow typing it correctly, but they don't exist. Everything else is just hinting / hacks around weak type system.

**Comment by spawnia** [comment]
I am still not quite sure whether `NodeList` or `NodeList|SomeTypeOfNode[]` is better. Both are certainly superior to `SomeTypeOfNode[]|NodeList`.

The issue i have with annotating multiple types is that it leads the unknowing developer to believe that it could be both, when in reality it is always a `NodeList`. However, that loses the information about what type is actually used. 

It is a bit unconventional, but we might actually put the diamond operator in the DocBlock. While that is not a part of any standard whatsoever, it actually leads to the correct type being recognized, but also informs a developer of the underlying type. At least it works in PHPStorm.

![image](https://user-images.githubusercontent.com/12158000/44383769-2bf4db00-a51a-11e8-87c3-bbd7940a9cba.png)

**Comment by robbieaverill** [comment]
It's worth noting that the _abandoned_ PSR-5 PHPDoc standard does support collections: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#collections

According to the PHP-FIG mailing list, PSR-5 was [split](https://github.com/php-fig/fig-standards/pull/1038) and looks like there are members trying to [reboot it](https://github.com/php-fig/fig-standards/pull/1026)

**Comment by vladar** [comment]
Closing stale issues. Open new follow-up issues if required.
